# Generated by Django 3.1.6 on 2021-04-09 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PersonnelName', models.CharField(max_length=3, verbose_name='人員名字')),
                ('PersonnelPhone', models.CharField(max_length=10, verbose_name='人員電話')),
                ('PersonnelJob', models.CharField(choices=[('0', '主管'), ('1', '一般人員'), ('2', 'PM'), ('3', '工程師')], max_length=1, verbose_name='人員等級')),
            ],
            options={
                'verbose_name': '人員資料',
            },
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CaseName', models.CharField(max_length=3, verbose_name='專案名字')),
                ('CaseMoney', models.CharField(max_length=3, verbose_name='專案金額')),
                ('CaseStatus', models.CharField(max_length=3, verbose_name='專案完成狀態')),
                ('CaseOwner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRUD_DEMO.personnel', verbose_name='專案管理者')),
            ],
            options={
                'verbose_name': '專案管理',
            },
        ),
    ]
